import { motion } from "framer-motion";
import { ArrowLeft, Copyright as CopyrightIcon } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { SpiritualButton } from "@/components/ui/spiritual-button";

const Copyright = () => {
  const navigate = useNavigate();
  const currentYear = new Date().getFullYear();

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      className="min-h-screen bg-background"
    >
      <header className="sticky top-0 z-50 bg-background/80 backdrop-blur-lg border-b border-border safe-area-top">
        <div className="container mx-auto px-4 py-4 flex items-center gap-4">
          <SpiritualButton variant="ghost" size="icon" onClick={() => navigate(-1)}>
            <ArrowLeft className="w-5 h-5" />
          </SpiritualButton>
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-full bg-gradient-spiritual flex items-center justify-center">
              <CopyrightIcon className="w-5 h-5 text-primary-foreground" />
            </div>
            <span className="font-display font-bold text-xl">Copyright Notice</span>
          </div>
        </div>
      </header>

      <main className="container mx-auto px-4 py-6 space-y-6 max-w-3xl">
        <p className="text-sm text-muted-foreground">Effective: January 1, {currentYear}</p>

        <section className="space-y-3">
          <h2 className="text-lg font-bold">1. Copyright Ownership</h2>
          <p className="text-muted-foreground leading-relaxed">
            © {currentYear} Stellar. All rights reserved. The Stellar application, including but not limited to its source code, user interface design, graphics, icons, logos, images, text content, audio elements, animations, data compilations, and overall look and feel, is the exclusive intellectual property of Stellar and its licensors. No portion of this application may be reproduced, distributed, modified, displayed, performed, published, or transmitted in any form or by any means without the prior written permission of Stellar.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-bold">2. Trademarks</h2>
          <p className="text-muted-foreground leading-relaxed">
            "Stellar," the Stellar logo, and all related names, logos, product and service names, designs, and slogans are trademarks of Stellar or its affiliates. You may not use such marks without the prior written permission of Stellar. All other names, logos, product and service names, designs, and slogans appearing in this application are the trademarks of their respective owners.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-bold">3. Content Ownership & License</h2>
          <p className="text-muted-foreground leading-relaxed">
            All astrological content, interpretations, analyses, reports, charts, and readings generated by Stellar — whether produced by artificial intelligence models or human experts — are the property of Stellar. Users are granted a limited, non-exclusive, non-transferable, revocable license to access and use such content solely for personal, non-commercial purposes within the application.
          </p>
          <p className="text-muted-foreground leading-relaxed">
            This license does not permit: (a) redistribution, resale, or commercial exploitation of any generated content; (b) systematic downloading or archiving of content for purposes beyond personal reference; (c) creation of derivative works based on Stellar content without express written consent; (d) use of content in competing applications or services.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-bold">4. User-Generated Content</h2>
          <p className="text-muted-foreground leading-relaxed">
            By submitting content to Stellar (including but not limited to reviews, feedback, profile information, photos for palm reading, and consultation messages), you grant Stellar a worldwide, non-exclusive, royalty-free, perpetual, irrevocable license to use, reproduce, modify, adapt, publish, translate, and distribute such content in connection with operating and improving the service. You represent and warrant that you own or have the necessary rights to grant this license and that your content does not infringe upon the intellectual property rights of any third party.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-bold">5. AI-Generated Content</h2>
          <p className="text-muted-foreground leading-relaxed">
            Stellar uses artificial intelligence models to generate astrological readings, analyses, and insights. The outputs of these AI models are produced specifically for the requesting user and constitute derivative works of Stellar's proprietary systems. While users may reference their personal readings for personal use, the underlying AI models, training data, algorithms, prompt engineering, and output generation methods remain the exclusive intellectual property of Stellar.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-bold">6. Third-Party Content & Attributions</h2>
          <p className="text-muted-foreground leading-relaxed">
            Stellar may incorporate third-party libraries, frameworks, fonts, icons, and other assets used under their respective open-source or commercial licenses. Such components remain the property of their respective copyright holders and are used in compliance with their license terms. A list of significant third-party components and their licenses is available upon written request.
          </p>
          <p className="text-muted-foreground leading-relaxed">
            Vedic astrology concepts, planetary calculation methods, and traditional astrological systems referenced in this application are part of the public domain and cultural heritage of Vedic traditions. Stellar does not claim ownership over these traditional knowledge systems.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-bold">7. Digital Millennium Copyright Act (DMCA)</h2>
          <p className="text-muted-foreground leading-relaxed">
            Stellar respects the intellectual property rights of others. If you believe that any content available through Stellar infringes your copyright, you may submit a DMCA takedown notice to our designated copyright agent at:
          </p>
          <div className="text-muted-foreground leading-relaxed pl-4 border-l-2 border-primary/30">
            <p><strong>Copyright Agent</strong></p>
            <p>Stellar Legal Department</p>
            <p>Email: legal@stellarapp.co</p>
          </div>
          <p className="text-muted-foreground leading-relaxed">
            Your notice must include: (a) identification of the copyrighted work claimed to be infringed; (b) identification of the infringing material and its location within the application; (c) your contact information; (d) a statement of good faith belief that the use is not authorized; (e) a statement under penalty of perjury that the information is accurate and you are authorized to act on behalf of the copyright owner; (f) your physical or electronic signature.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-bold">8. Restrictions on Use</h2>
          <p className="text-muted-foreground leading-relaxed">
            You agree not to: (a) copy, modify, or distribute any part of the application without authorization; (b) reverse engineer, decompile, or disassemble the application or any component thereof; (c) remove, alter, or obscure any copyright, trademark, or other proprietary notices; (d) use any automated systems (bots, scrapers, crawlers) to access or extract content from the application; (e) frame, mirror, or incorporate any part of the application into another product or service; (f) sublicense, sell, rent, or lease access to the application or its content.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-bold">9. Enforcement & Remedies</h2>
          <p className="text-muted-foreground leading-relaxed">
            Stellar actively monitors for and enforces its intellectual property rights. Unauthorized use of any copyrighted material may result in: (a) immediate termination of your account and access to the application; (b) civil action seeking damages, injunctive relief, and attorney's fees; (c) criminal prosecution where applicable under copyright law. Stellar reserves all rights and remedies available under applicable law.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-bold">10. International Copyright</h2>
          <p className="text-muted-foreground leading-relaxed">
            Stellar content is protected by copyright laws of India, the United States, and international copyright treaties including the Berne Convention and the WIPO Copyright Treaty. Unauthorized use in any jurisdiction may subject the infringer to both civil and criminal penalties.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-bold">11. Contact</h2>
          <p className="text-muted-foreground leading-relaxed">
            For permissions, licensing inquiries, or copyright-related questions, please contact us at legal@stellarapp.co.
          </p>
        </section>

        <div className="h-8" />
      </main>
    </motion.div>
  );
};

export default Copyright;
